# Generated by Django 3.2.9 on 2022-01-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='graduation_status',
            field=models.CharField(blank=True, choices=[('enrolled', 'Enrolled'), ('graduated', 'Graduated')], max_length=255),
        ),
    ]
