# Generated by Django 3.2.9 on 2022-01-06 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_auto_20220106_0320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Connection_Request',
            new_name='ConnectionRequest',
        ),
    ]
