# Generated by Django 3.2.9 on 2022-01-06 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_rename_connection_request_connectionrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectionrequest',
            old_name='to_user',
            new_name='to_profile',
        ),
    ]
