# Generated by Django 3.2.9 on 2022-01-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_rename_to_user_connectionrequest_to_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=255),
        ),
    ]
