# Generated by Django 3.2.9 on 2022-01-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_alter_experience_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='years',
            field=models.CharField(blank=True, choices=[('0-1', '0-1 Years'), ('1-3', '1-3 Years'), ('3-0', '3-Up Years')], max_length=255),
        ),
    ]
